# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rapid-git
email:
description: > # this means to ignore newlines until "baseurl:"
  rapid-git provides shortcuts for often-used git commands, which aim to make your daily git use more efficient by typing less.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rapid-git.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  rapid-git

# Build settings
markdown: kramdown
